# XDG
XDG_CONFIG_HOME=%h/.config
XDG_DATA_HOME=%h/.local/share
XDG_CACHE_HOME=%h/.cache
XDG_STATE_HOME=%h/.local/state

# Locale
LANG=pt_BR.UTF-8
LC_NUMERIC=en_US.UTF-8

# Editor
EDITOR=nvim
VISUAL=nvim
